spring:

  datasource:
    #url: jdbc:h2:mem:testdb
    #url: jdbc:mysql://localhost:3306/phones
    url: jdbc:mysql://localhost:3306/phones?useSSL=false&serverTimezone=UTC
    username: root
    password:

  jpa:
    show-sql: true
    #hibernate:
      #format_sql: true

  #h2:
    #console:
      #enabled: true
      #path: /h2-console
      #dialect: SQL

  #security:
    #basic:
      #enabled: false
