spring:

  datasource:
    #url: jdbc:mysql://localhost:3306/phones
    url: jdbc:mysql://localhost:3306/phones?useSSL=false&serverTimezone=UTC
    username: root
    password:

  jpa:
    show-sql: true